In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('Train.csv')
df.drop(df.iloc[:,15:], inplace = True, axis = 1)
df.drop(df.iloc[:,8:], inplace = True, axis = 1)
df.drop(df.iloc[:,2:4], inplace = True, axis = 1)
x = df.iloc[:,1:].values

In [2]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
l_x = LabelEncoder()
x[:,0] = l_x.fit_transform(x[:,0])
x[:,1] = l_x.fit_transform(x[:,1])
x[:,2] = l_x.fit_transform(x[:,2])
x[:,3] = l_x.fit_transform(x[:,3])
x[:,4] = l_x.fit_transform(x[:,4])
#print(x)
ohc = OneHotEncoder()
x = pd.DataFrame(ohc.fit_transform(x).toarray())
print(x)

       0    1    2    3    4    5    6    7    8    9   ...   15   16   17  \
0     1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1     0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
2     1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
3     1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4     1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
6995  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6996  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6997  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
6998  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0   
6999  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

       18   19   20   21   22   23   24  
0     0.0  0.0  0.0  

In [3]:
df1 = pd.read_csv('Train.csv')
df1.drop(df1.iloc[:,14:15], inplace = True, axis = 1)
df1.drop(df1.iloc[:,:8], inplace = True, axis = 1)
df2 = df1.join(x)
df2.head(5)

Time_of_service  Time_since_promotion  growth_rate  Travel_Rate  \
0              4.0                     4           33            1   
1              5.0                     4           36            0   
2             27.0                     3           51            0   
3              4.0                     3           56            1   
4              5.0                     4           62            1   

   Post_Level  Pay_Scale  Work_Life_balance  VAR1    VAR2    VAR3  ...   15  \
0           1        7.0                3.0     4  0.7516  1.8688  ...  0.0   
1           3        6.0                4.0     3 -0.9612 -0.4537  ...  0.0   
2           2        8.0                1.0     4 -0.9612 -0.4537  ...  0.0   
3           3        8.0                1.0     3 -1.8176 -0.4537  ...  0.0   
4           3        2.0                3.0     1  0.7516 -0.4537  ...  0.0   

    16   17   18   19   20   21   22   23   24  
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  

[5 rows x 40 columns]

In [4]:
dfc = pd.read_csv('Train.csv')
x_r = dfc.iloc[:,2:4].values
x_r1 = pd.DataFrame(x_r)
x_r1.columns = [25 , 26]
print(x_r1)

        25   26
0     42.0  4.0
1     24.0  3.0
2     58.0  3.0
3     26.0  3.0
4     31.0  1.0
...    ...  ...
6995  23.0  5.0
6996  44.0  1.0
6997  49.0  3.0
6998  47.0  3.0
6999  58.0  3.0

[7000 rows x 2 columns]


In [5]:
dfn = df2.join(x_r1)
dfn.head(5)

Time_of_service  Time_since_promotion  growth_rate  Travel_Rate  \
0              4.0                     4           33            1   
1              5.0                     4           36            0   
2             27.0                     3           51            0   
3              4.0                     3           56            1   
4              5.0                     4           62            1   

   Post_Level  Pay_Scale  Work_Life_balance  VAR1    VAR2    VAR3  ...   17  \
0           1        7.0                3.0     4  0.7516  1.8688  ...  0.0   
1           3        6.0                4.0     3 -0.9612 -0.4537  ...  0.0   
2           2        8.0                1.0     4 -0.9612 -0.4537  ...  1.0   
3           3        8.0                1.0     3 -1.8176 -0.4537  ...  0.0   
4           3        2.0                3.0     1  0.7516 -0.4537  ...  0.0   

    18   19   20   21   22   23   24    25   26  
0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  42.0  4.0  
1  0.0  0.0  0.0  1.0  0.0  0.0  0.0  24.0  3.0  
2  0.0  0.0  0.0  0.0  0.0  1.0  0.0  58.0  3.0  
3  0.0  0.0  0.0  0.0  1.0  0.0  0.0  26.0  3.0  
4  0.0  0.0  0.0  0.0  0.0  1.0  0.0  31.0  1.0  

[5 rows x 42 columns]

In [6]:
y_t = dfn.iloc[:, 14].values
dfn.drop(dfn.iloc[:,14:15], inplace = True, axis = 1)
x_t = dfn.iloc[:,:].values


from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values = np.nan , strategy = 'mean')
imp = imp.fit(x_t)
x_t = imp.transform(x_t)

#from sklearn.preprocessing import StandardScaler
#scx = StandardScaler()
#x_t = scx.fit_transform(x_t)

print(y_t)
print(x_t.shape)

[0.1841 0.067  0.0851 ... 0.7847 0.4162 0.091 ]
(7000, 41)


In [7]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_t,y_t)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
td = pd.read_csv('Test.csv')
td.drop(td.iloc[:,8:], inplace = True, axis = 1)
td.drop(td.iloc[:,2:4], inplace = True, axis = 1)
x_tt = td.iloc[:,1:].values

l_x1 = LabelEncoder()
x_tt[:,0] = l_x1.fit_transform(x_tt[:,0])
x_tt[:,1] = l_x1.fit_transform(x_tt[:,1])
x_tt[:,2] = l_x1.fit_transform(x_tt[:,2])
x_tt[:,3] = l_x1.fit_transform(x_tt[:,3])
x_tt[:,4] = l_x1.fit_transform(x_tt[:,4])
#print(x)
ohc1 = OneHotEncoder()
x_tt = pd.DataFrame(ohc1.fit_transform(x_tt).toarray())
print(x_tt)

       0    1    2    3    4    5    6    7    8    9   ...   15   16   17  \
0     1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
1     0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2     0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
3     0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0   
4     1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
2995  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2996  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2997  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2998  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
2999  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

       18   19   20   21   22   23   24  
0     1.0  0.0  0.0  

In [9]:
df3 = pd.read_csv('Test.csv')
df3.drop(df3.iloc[:,14:15], inplace = True, axis = 1)
df3.drop(df3.iloc[:,:8], inplace = True, axis = 1)
df4 = df3.join(x_tt)
df4.head(5)

Time_of_service  Time_since_promotion  growth_rate  Travel_Rate  \
0              7.0                     4           30            1   
1             41.0                     2           72            1   
2             21.0                     3           25            0   
3             11.0                     4           28            1   
4             12.0                     4           47            1   

   Post_Level  Pay_Scale  Work_Life_balance  VAR1    VAR2    VAR3  ...   15  \
0           5        4.0                1.0     3 -0.9612 -0.4537  ...  0.0   
1           1        1.0                1.0     4 -0.9612  0.7075  ...  0.0   
2           1        8.0                1.0     4 -0.1048  0.7075  ...  0.0   
3           1        2.0                4.0     3 -0.1048  0.7075  ...  0.0   
4           3        2.0                4.0     4  1.6081  0.7075  ...  0.0   

    16   17   18   19   20   21   22   23   24  
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
2  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  
3  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  
4  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  

[5 rows x 39 columns]

In [10]:
dfct = pd.read_csv('Train.csv')
x_rt = dfc.iloc[:,2:4].values
x_rt1 = pd.DataFrame(x_rt)
x_rt1.columns = [25 , 26]
print(x_rt1)

        25   26
0     42.0  4.0
1     24.0  3.0
2     58.0  3.0
3     26.0  3.0
4     31.0  1.0
...    ...  ...
6995  23.0  5.0
6996  44.0  1.0
6997  49.0  3.0
6998  47.0  3.0
6999  58.0  3.0

[7000 rows x 2 columns]


In [11]:
dff = df4.join(x_r1)
dff.head(5)

Time_of_service  Time_since_promotion  growth_rate  Travel_Rate  \
0              7.0                     4           30            1   
1             41.0                     2           72            1   
2             21.0                     3           25            0   
3             11.0                     4           28            1   
4             12.0                     4           47            1   

   Post_Level  Pay_Scale  Work_Life_balance  VAR1    VAR2    VAR3  ...   17  \
0           5        4.0                1.0     3 -0.9612 -0.4537  ...  0.0   
1           1        1.0                1.0     4 -0.9612  0.7075  ...  0.0   
2           1        8.0                1.0     4 -0.1048  0.7075  ...  0.0   
3           1        2.0                4.0     3 -0.1048  0.7075  ...  0.0   
4           3        2.0                4.0     4  1.6081  0.7075  ...  0.0   

    18   19   20   21   22   23   24    25   26  
0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  42.0  4.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  1.0  24.0  3.0  
2  0.0  1.0  0.0  0.0  0.0  0.0  1.0  58.0  3.0  
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  26.0  3.0  
4  1.0  0.0  0.0  0.0  0.0  1.0  0.0  31.0  1.0  

[5 rows x 41 columns]

In [12]:
x_test = dff.iloc[:,:].values

imp2 = SimpleImputer(missing_values = np.nan , strategy = 'mean')
imp2 = imp.fit(x_test)
x_test = imp.transform(x_test)


print(x_test)

[[ 7.  4. 30. ...  0. 42.  4.]
 [41.  2. 72. ...  1. 24.  3.]
 [21.  3. 25. ...  1. 58.  3.]
 ...
 [35.  1. 69. ...  0. 31.  4.]
 [23.  1. 30. ...  0. 24.  3.]
 [12.  4. 70. ...  1. 48.  4.]]


In [ ]:
y_pred = model.predict(x_test)
print(y_pred)

In [ ]:
#my_submission = pd.DataFrame({'Attrition_rate': y_pred})
#my_submission.to_csv('submission3.csv', index = False)


In [24]:
import xgboost as xgb
xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 10, alpha = 10, n_estimators = 100)
xg_reg.fit(x_t,y_t)

preds = xg_reg.predict(x_test)
print(preds)

[15:10:00] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[0.27272677 0.24744862 0.22783127 ... 0.21785358 0.22683153 0.20321721]


In [18]:
my_submission = pd.DataFrame({'Attrition_rate': preds})
my_submission.to_csv('submission9.csv', index = False)